language: python

# set up containerized builds with cacheing
sudo: false

cache:
  directories:
    - $HOME/miniconda

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - CONDA_DEPS="numpy scipy nose scikit-learn"

before_install:
  - export MINICONDA=$HOME/miniconda
  - export PATH=$MINICONDA/bin:$PATH
  - command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
     bash miniconda.sh -b -f -p $MINICONDA; }
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS

install:
  - python setup.py install --record installed_files.txt

script:
  - nosetests --with-doctest wpca

before_cache:
  # clean unused packages & remove installed files from cache
  - conda clean --tarballs --packages --index-cache
  - rm -rf $HOME/miniconda/pkgs/cache
  - xargs rm <installed_files.txt
